FROM python:3.13-slim
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend.py .
EXPOSE 8001
CMD [ "uvicorn", "backend:app", "--host", "0.0.0.0", "--port" , "8001" ]